const activities = [
    { type: 'PLAYING',  message: 'PENTAKILL'  },
    { type: 'PLAYING',  message: "Bouge pas ! J'essaie de te descendre ! "  },
    { type: 'PLAYING',  message: "Je vais compter jusqu'à... ZÉRO ! "  },
    { type: 'PLAYING',  message: "À l'abri ! Je plaisante, ça t'aidera pas !"  },
    { type: 'PLAYING',  message: "Il faut bien mourir un jour. "  },
    { type: 'PLAYING',  message: "Souriez, le petit boulet va sortir ! "  },
    { type: 'PLAYING',  message: "Une dernière volonté ? Ahaha ! Pas le temps ! "  },
    { type: 'PLAYING',  message: "À quoi ça t'avance de pleurer, hein ? "  },
    { type: 'PLAYING',  message: "Inutile d'avoir peur, ni d'être en vie."  },
    { type: 'PLAYING',  message: "Ah, tu m'ennuies."  },
    { type: 'PLAYING',  message: "J'ai fait ça volontairement, par accident."  },
    { type: 'PLAYING',  message: "J'adore gaspiller des balles sur toi."  },
    { type: 'PLAYING',  message: "Mais tu vas rire, oui ?"  },
    { type: 'PLAYING',  message: "Ta ta ta ta ta ta ta ta ta ta ta..."  },
    { type: 'PLAYING',  message: "Pow !"  },
    { type: 'PLAYING',  message: "Je veux vous voir paniquer ! "  },
    { type: 'PLAYING',  message: "De la dignité. Je t'en donnerai de la dignité !"  },
    { type: 'PLAYING',  message: "Réfléchissons. Ah, et puis non, tiens."  },
    { type: 'PLAYING',  message: "J'ai failli avoir de la compassion et finalement, non."  },
    { type: 'PLAYING',  message: "Jinx, c'est pour Jinx."  },
    { type: 'PLAYING',  message: "Ah oui ? Mais bon, quand est-ce qu'on tire ?"  },
    { type: 'PLAYING',  message: "J'en étais où ? Ah oui, le chaos !"  },
    { type: 'PLAYING',  message: "Attends, je vais te dire quelque chose de cool !"  },
    { type: 'PLAYING',  message: `Demande-moi si j'écoute. "Spoiler", non !`  },
    { type: 'PLAYING',  message: "D'abord on fait sauter, ensuite on réfléchit ! "  },
    { type: 'PLAYING',  message: "Tu pense que je suis folle ? Tu devrais voir ma sœur."  },
    { type: 'PLAYING',  message: "J'ai de bonnes intentions !"  },
    { type: 'PLAYING',  message: "J'ai des tas de ceintures. Tiens, pourquoi d'ailleurs ?"  },
    { type: 'PLAYING',  message: "Des balles !"  },
    { type: 'PLAYING',  message: "Qui a besoin de raison ?"  },
    { type: 'PLAYING',  message: "Je suis folle ! Mais j'ai un mot d'excuse du toubib."  },
    { type: 'PLAYING',  message: "Mon plan se déroule comme prévu !"  },
    { type: 'PLAYING',  message: "Et si j'avais un fusil pour... exploser d'autres fusils !"  },
    { type: 'PLAYING',  message: "Ah, allez ! C'est pas comme si on risquait de se blesser."  },
    { type: 'PLAYING',  message: "J'ai vraiment besoin d'un nouveau flingue. Mais, ne le dites pas à mes autres armes !"  },
    { type: 'PLAYING',  message: "Personne ne me mettra en violon."  },
    { type: 'PLAYING',  message: "Hé, Poiscaille, si on faisait péter un truc ?"  },
    { type: 'PLAYING',  message: "Tu risques de déranger les gens et de les attrister."  },
    { type: 'PLAYING',  message: "Génial, j'ai une arme pacifiste !"  },
    { type: 'PLAYING',  message: "Poiscaille, tu sais ce qu'on devrait faire ?"  },
    { type: 'PLAYING',  message: "La vaisselle, le ménage, et le repassage !"  },
    { type: 'PLAYING',  message: "Pff, débile ce lance-roquettes."  },
    { type: 'PLAYING',  message: "Hé, Poiscaille, c'est la belle vie de semer le chaos, hein ?"  },
    { type: 'PLAYING',  message: "Non, tu devrais acheter une maison et économiser pour ta retraite."  },
    { type: 'PLAYING',  message: "Je peux te remplacer, tu sais !"  },
    { type: 'PLAYING',  message: "On devrait se poser à la campagne et profiter de la vie."  },
    { type: 'PLAYING',  message: "C'est vrai ? J'ai toujours espéré qu'un jour..."  },
    { type: 'PLAYING',  message: "Ahaha ! Je t'ai eu. Tu es une machine à tuer pour toujours !"  },
    { type: 'PLAYING',  message: "Les armes ne tuent pas... Sauf quand on tire sur les gens. Dans ce cas, elles explosent tout !"  },
    { type: 'PLAYING',  message: "Inutile d'être à couteau tiré, j'ai des flingues !"  },
    { type: 'PLAYING',  message: "On dit bonjour à mes petits amis de toutes les tailles !"  },
    { type: 'PLAYING',  message: "J'ai trois flingues, alors je fais ce que je veux."  },
    { type: 'PLAYING',  message: "Hé, Miss Chapeau, tu veux un costume en sapin ?"  },
    { type: 'PLAYING',  message: "Un seul flingue, Miss Chapeau ? Oh, quelle misère."  },
    { type: 'PLAYING',  message: "Tu vas me poursuivre, Grosses Mains ?"  },
    { type: 'PLAYING',  message: "Vi, c'est pour idiote !"  },
    { type: 'PLAYING',  message: "Je suis là, Grosses Mains !"  },
    { type: 'PLAYING',  message: "Zap !"  },
    { type: 'PLAYING',  message: "À la revoyure !"  },
    { type: 'PLAYING',  message: "Adieu."  },
    { type: 'PLAYING',  message: "Regardez tous !"  },
    { type: 'PLAYING',  message: "Attrape !"  },
    { type: 'PLAYING',  message: "J'ai mal ! J'ai dû me casser un ongle."  },
    { type: 'PLAYING',  message: "C'était presque complètement raté."  },
    { type: 'PLAYING',  message: "Trois, quarante-et-un , neuf, DÉCOLLAGE !"  },
    { type: 'PLAYING',  message: " Je reviens, attendez-moi pour mourir ! "  },
    { type: 'WATCHING', message: 'JavaScript >>> Python' },
    { type: 'WATCHING', message: 'Get Jinxed' },
    { type: 'PLAYING',  message: '"Powder!h" pour les commandes de musique'  },
    { type: 'PLAYING',  message: '"Jinx!h" pour les commandes générales'  },
];

const statut_choix = [
    'idle',
    'dnd',
    'online'
];

function bio() {
    return activities[Math.floor(Math.random() * (activities.length - 1) + 1)];
}

function status(){
    return statut_choix[Math.floor(Math.random() * (statut_choix.length - 1) + 1)];
}

module.exports = { bio, status }